browse/routes/dissemination.py
"""Routes for PDF, source and other downloads."""
from typing import Optional, Dict

from arxiv.identifier import Identifier, IdentifierException
from browse import b_add_surrogate_key
from flask import Blueprint, redirect, url_for, Response, render_template, request
from werkzeug.datastructures import Headers
from werkzeug.exceptions import InternalServerError, BadRequest

from browse.controllers import check_supplied_identifier
from browse.controllers.files.dissemination import get_html_response, get_pdf_resp, get_ps_response
from browse.services.documents import get_doc_service

blueprint = Blueprint('dissemination', __name__)


@blueprint.route("/pdf/<string:archive>/<string:arxiv_id>.pdf", methods=['GET', 'HEAD'])
@blueprint.route("/pdf/<string:arxiv_id>.pdf", methods=['GET', 'HEAD'])
def redirect_pdf(arxiv_id: str, archive=None):  # type: ignore
    """Redirect URLs with .pdf to a URL without.

    In past a redirect from /pdf/paperid to /pdf/paperid.pdf was used to cause
    the browser to download the file with the .pdf extension. This is to support
    any user who has bookmarked or saved a PDF URL with the .pdf extension in
    the past, so they will get a redirect to the "normal" PDF URL. I think we
    started using the redirect because of an ignorance of the "inline" mode of
    the content-disposition header.

    Now a content-disposition is used. It is a standard mechanism that is part
    of HTTP to provide a way for the server to specify what the file name should
    be on download.

    The content-disposition preservers the "if I download this to my computer,
    save it in a file named {paper_id}.pdf" behavior, and it does that in a
    direct and standard way. It also eliminates the redirect, which is wasteful
    and only indirectly communicates the download file name.

    """
    arxiv_id = f"{archive}/{arxiv_id}" if archive else arxiv_id
    return redirect(url_for('.pdf', arxiv_id=arxiv_id), 301)


@blueprint.route("/pdf/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/pdf/<string:arxiv_id>", methods=['GET', 'HEAD'])
def pdf(arxiv_id: str, archive=None):  # type: ignore
    """Want to handle the following patterns:

        /pdf/{archive}/{id}v{v}
        /pdf/{id}v{v}

    The dissemination service does not handle versionless
    requests. The version should be figured out in some other service
    and redirected to the CDN.

    Does a 400 if the ID is malformed or lacks a version.

    Does a 404 if the key for the ID does not exist on the bucket.
    """

    if request.query_string:  # redirect to strip off any useless query strings
        return redirect(url_for('.pdf', arxiv_id=arxiv_id, archive=archive), 301)
    return get_pdf_resp(arxiv_id, archive)


@blueprint.route("/format/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/format/<string:arxiv_id>", methods=['GET', 'HEAD'])
def format(arxiv_id: str, archive: Optional[str] = None) -> Response:
    """Get formats article."""
    arxiv_id = f"{archive}/{arxiv_id}" if archive else arxiv_id
    try:
        arxiv_identifier = Identifier(arxiv_id=arxiv_id)
    except IdentifierException:
        raise BadRequest(f"Bad paper identifier: {arxiv_id}")

    redirect_url = check_supplied_identifier(arxiv_identifier, "dissemination.format")
    if redirect_url:
        return redirect_url  # type: ignore

    abs_meta = get_doc_service().get_abs(arxiv_id)
    data = {"arxiv_id": arxiv_identifier.id, "arxiv_idv": arxiv_identifier.idv, "abs_meta": abs_meta,
            "encrypted": abs_meta.get_requested_version().source_flag.source_encrypted}

    formats = data["formats"] = abs_meta.get_requested_version().formats()

    if abs_meta.get_requested_version().source_format == "pdftex":  # ARXIVCE-3376 no ps for pdflatex
        formats = [fmt for fmt in formats if fmt != "ps"]

    for fmt in formats:
        data[fmt] = True
    # TODO DOCX doesn't seem like the url_for in the template will work correctly with the .docx?
    headers: Headers | Dict[str, str] = {}
    headers = b_add_surrogate_key(headers, ["format", f"paper-id-{arxiv_identifier.id}"])
    if arxiv_identifier.has_version:
        headers = b_add_surrogate_key(headers, [f"paper-id-{arxiv_identifier.idv}"])
    else:
        headers = b_add_surrogate_key(headers, [f"paper-id-{arxiv_identifier.id}-current"])
    return render_template("format.html", **data), 200, headers  # type: ignore


@blueprint.route("/dvi/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/dvi/<string:arxiv_id>", methods=['GET', 'HEAD'])
def dvi(arxiv_id: str) -> Response:
    """Get DVI for article."""
    raise InternalServerError(f"Not yet implemented {arxiv_id}")


@blueprint.route("/html/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/html/<string:archive>/<path:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/html/<string:arxiv_id>/", methods=['GET', 'HEAD'])
def html(arxiv_id: str, archive: Optional[str] = None):  # type: ignore
    """get html for article"""
    return get_html_response(arxiv_id, archive)


@blueprint.route("/ps/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/ps/<string:arxiv_id>", methods=['GET', 'HEAD'])
def ps(arxiv_id: str, archive: Optional[str] = None) -> Response:
    """Get ps for article."""
    return get_ps_response(arxiv_id, archive)

browse/routes/src.py
"""Routes for serving the source of articles. /src /e-prints and ancillary."""
import logging
from typing import Optional

from arxiv.identifier import Identifier, IdentifierException
from browse import b_add_surrogate_key

from browse.controllers.files.dissemination import get_src_resp
from browse.controllers.files.ancillary_files import get_extracted_src_file_resp
from browse.services.dissemination import get_article_store
from browse.services.documents import get_doc_service
from flask import Blueprint, Response, make_response, render_template
from opentelemetry import trace

logger = logging.getLogger(__file__)
logger.setLevel(logging.INFO)

blueprint = Blueprint('src', __name__)

tracer = trace.get_tracer(__name__)


@blueprint.route("/src/<path:arxiv_id>/anc")
def anc_listing(arxiv_id: str):  #type: ignore
    """Serves listing of ancillary files for a paper."""
    data: dict = {}
    docmeta = get_doc_service().get_abs(arxiv_id)
    data['abs_meta'] = docmeta
    data['arxiv_id'] = docmeta.arxiv_identifier
    data['anc_file_list'] = get_article_store().get_ancillary_files(docmeta)

    if data['anc_file_list']:
        resp=make_response(render_template("src/listing.html", **data))
        _src_surrogate_keys(resp, arxiv_id, True)
        return resp
    else:
        resp=make_response(render_template("src/listing_none.html", **data))
        _src_surrogate_keys(resp, arxiv_id, True)
        resp.status_code=404
        return resp


@blueprint.route("/src/<path:arxiv_id>/anc/<path:file_path>")
def anc(arxiv_id: str, file_path:str):  # type: ignore
    """Serves ancillary files or show html page of ancillary files

    Returns just the specified file within the source package. Has
    meaning only for .tar.gz packages and will most frequently be used to access
    ancillary files such as /src/anc/some_file

    ex https://arxiv.org/src/1911.08265v1/anc
    ex https://arxiv.org/src/1911.08265v1/anc/pseudocode.py
    """
    resp=get_extracted_src_file_resp(arxiv_id, f"anc/{file_path}", 'anc')
    _src_surrogate_keys(resp, arxiv_id, True)
    return resp


@blueprint.route("/e-print/<string:arxiv_id_str>")
@blueprint.route("/e-print/<string:archive>/<string:arxiv_id_str>")
@blueprint.route("/src/<string:arxiv_id_str>")
@blueprint.route("/src/<string:archive>/<string:arxiv_id_str>")
def src(arxiv_id_str: str, archive: Optional[str]=None):  # type: ignore
    """Serves the source of a requested paper.

    This serves it in the original format submitted. Before 2024 it would .tar up
    single file submissions.

    The e-print path serves the source of a requested paper as original format submitted and
    form that we store it (.tar.gz, .pdf, etc.). It is used to support the mirrors.
    Before 2024 /src behavior was different than /e-print.
     """
    resp=get_src_resp(arxiv_id_str, archive) #always adds a verion onto the id
    _src_surrogate_keys(resp, arxiv_id_str)
    return resp


def _src_surrogate_keys(resp: Response, arxiv_id_str: str, anc:bool=False) -> None:
    resp.headers=b_add_surrogate_key(resp.headers,["src"])
    if _check_id_for_version(arxiv_id_str):
        resp.headers=b_add_surrogate_key(resp.headers,[f"src-{arxiv_id_str}",
                                                     f"paper-id-{arxiv_id_str}"])
    else:
        resp.headers=b_add_surrogate_key(resp.headers,[f"src-{arxiv_id_str}-current",
                                                     f"paper-id-{arxiv_id_str}-current"])

    if anc:
        resp.headers=b_add_surrogate_key(resp.headers,["anc"])
        if _check_id_for_version(arxiv_id_str):
            resp.headers=b_add_surrogate_key(resp.headers,[f"anc-{arxiv_id_str}"])
        else:
            resp.headers=b_add_surrogate_key(resp.headers,[f"anc-{arxiv_id_str}-current"])


def _check_id_for_version(arxiv_id_str:str) -> bool:
    """returns true if the url was asking for a specific paper version, false otherwise"""
    try:
        arxiv_id= Identifier(arxiv_id_str)
        if arxiv_id.has_version:
            return True
        else:
            return False
    except IdentifierException:
        return False

browse/services/dissemination/__init__.py
"""Service to get PDF and other disseminations of an item."""
from arxiv.legacy.papers.dissemination.reasons import get_reasons_data
from flask import current_app
import logging

from browse.services.documents import get_doc_service
from browse.services.global_object_store import get_global_object_store, one_time_file

from .article_store import ArticleStore

logger = logging.getLogger(__name__)

_article_store: ArticleStore = None  # type: ignore
# This works because it is thread safe and not bound to the app context.


def get_article_store() -> "ArticleStore":
    """Gets the `ArticleStore` service.

    This returns PDF and other formats of the article."""
    global _article_store
    if _article_store is None:
        config = current_app.config

        dsp_os = get_global_object_store(config["DISSEMINATION_STORAGE_PREFIX"], "_object_store")
        if config["REASONS_FILE_PATH"] == "DEFAULT":
            reason_file = dsp_os.to_obj("reasons.json")
        else:
            logger.info("Loading reasons file from %s", config["REASONS_FILE_PATH"])
            reason_file = one_time_file(config["REASONS_FILE_PATH"])

        if config["SOURCE_STORAGE_PREFIX"] == config["DISSEMINATION_STORAGE_PREFIX"]:
            src_os = dsp_os
        else:
            src_os = get_global_object_store(config["SOURCE_STORAGE_PREFIX"], "_source_store")

        _article_store = ArticleStore(
            get_doc_service(),
            dsp_os,
            src_os,
            get_global_object_store(config["GENPDF_API_STORAGE_PREFIX"], "_genpdf_store"),
            get_global_object_store(config["LATEXML_BUCKET"], "_latexml_store"),
            get_reasons_data(reason_file),
        )

    return _article_store

browse/views.py
"""Provides the user intefaces for browse."""
from typing import Union

from browse.controllers import abs, get_institution_from_request
from flask import Blueprint, render_template, request, Response, session, \
                  redirect
from arxiv import status
from arxiv.base import exceptions
from werkzeug.exceptions import InternalServerError, NotFound, HTTPException

blueprint = Blueprint('browse', __name__, url_prefix='')


@blueprint.before_request
def before_request() -> None:
    """Get instituional affiliation from session."""
    if 'institution' not in session:
        institution = get_institution_from_request()
        session['institution'] = institution


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Hook for applying response headers to all responses."""
    """Prevent UI redress attacks"""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"
    return response


@blueprint.route('/abs', methods=['GET'])
def bare_abs():
    """Return 404."""
    raise NotFound


@blueprint.route('/abs/', methods=['GET'], defaults={'arxiv_id': ''})
@blueprint.route('/abs/<path:arxiv_id>', methods=['GET', 'POST'])
def abstract(arxiv_id: str) -> Union[str, Response]:
    """Abstract (abs) page view."""
    response, code, headers = abs.get_abs_page(arxiv_id, request.args)

    if code == status.HTTP_200_OK:
        return render_template('abs/abs.html', **response), code, headers
    elif code == status.HTTP_301_MOVED_PERMANENTLY:
        return redirect(headers['Location'], code=code)
    elif code == status.HTTP_404_NOT_FOUND:
        return render_template('abs/404.html', **response), code, headers

    raise InternalServerError('Unexpected error')

browse/templates/dissemination/bad_id.html
{% extends "base/base.html" %}

{# This is the template that gets shown when the client provides
something that is not a valid ID. #}

{%- block content -%}
<h1>No article for '{{arxiv_id.ids}}'</h1>
<p>The identifier you have specified '{{arxiv_id.ids}}' appears to be invalid.</p>

<p>{{err_msg}}</p>

<p>Please inform help@arxiv.org if you believe that the identifier should correspond to a valid paper in arXiv.</p>
{%- endblock -%}

browse/templates/dissemination/cannot_build_pdf.html
{% extends "base/base.html" %}

{%- block content -%}
<h1>{{fmt|upper}} Unavailable</h1>

<p>Our <b>automated</b> source to PDF conversion system was unable to produce PDF for the paper:
  <a href="{{url_for('browse.abstract', arxiv_id=arxiv_id.ids)}}">{{arxiv_id.ids}}</a>.</p>

<p>Incomplete or corrupted files were submitted. This failure can be resolved by replacing missing or corrupted files.<p>

<p>The reason for failure is recorded as: <b>{{msg}}</b></p>

<p>Return to the <a href="{{url_for('browse.abstract', arxiv_id=arxiv_id.ids)}}">abstract</a> for an
  alternative link to the
  <a href="{{url_for('src.src', arxiv_id_str=arxiv_id.ids)}}">source</a>, or to find an
  email address to contact the author.</p>

<p>For help regarding the automated source to PDF system,
  contact <a href="mailto:help@arxiv.org">help@arxiv.org</a>,
  remembering to specify the problematic archive and paper number.</p>

{%- endblock -%}

browse/templates/dissemination/multiple_files.html
{% extends "base/base.html" %}

{%- block title -%}{{arxiv_id.ids}}{%- endblock -%}

{%- block content -%}
<h1>The following files are available for {{ arxiv_id.idv }}</h1>
<ul>
    {% for file in file_names %}
        <li><a href="{{url_for('dissemination.html', arxiv_id=arxiv_id.idv)}}/{{file}}" title="{{file}}" id="{{ arxiv_id.ids }}-{{file}}" aria-labelledby="{{ arxiv_id.ids }}-{{file}}">{{file}}</a></li>
    {% endfor %}
</ul>
{%- endblock -%}

browse/templates/dissemination/no_html.html
{% extends "base/base.html" %}

{# This is when an html version is unavailable for some reason, 
    either we havent converted the latex or failed to, or its another type of document that isnt latex or native html #}

{%- block content -%}
<h1>No HTML for '{{arxiv_id.idv}}'</h1>
<p>HTML is not available for the source.</p>
<p>This could be due to the source files not being HTML, LaTeX, or a conversion failure.</p>
<p>If you are an author, learn how you can help <a href="https://info.arxiv.org/about/accessibility_html_error_messages.html">HTML conversions for your papers</a>.</p>
{%- endblock -%}

browse/templates/dissemination/no_source.html
{% extends "base/base.html" %}

{%- block title -%}No file for {{arxiv_id.ids}}{%- endblock -%}

{%- block content -%}
<h1>File unavailable for {{ arxiv_id.ids }}</h1>
<p>HTML or source was not provided to generate HTML or a PDF.</p>
{%- endblock -%}

browse/templates/dissemination/not_found.html
{% extends "base/base.html" %}

{# This is when the arxiv ID from the client is valid but the article
or version does not exist. #}

{%- block content -%}
<h1>No document for '{{arxiv_id.ids}}'</h1>
<p>Please inform help@arxiv.org if you believe that the identifier should correspond to a valid paper in arXiv.</p>
{%- endblock -%}

browse/templates/dissemination/not_pdf.html
{% extends "base.html" %}

{# This is the template that gets shown when the paper and version
exists, but the source is not PDF and the source cannot build a PDF. Ex HTML source #}

{%- block content -%}
<h1>{{arxiv_id.ids}} does not build PDF</h1>
<p>
  The source for the paper
  <a href="{{url_for('browse.abstract', arxiv_id=arxiv_id.ids)}}">{{arxiv_id.id}}</a>
  cannot built to a PDF by our systems.
</p>
{%- endblock -%}

browse/templates/dissemination/not_public.html
{% extends "base/base.html" %}

{%- block title -%}Not public {{arxiv_id.ids}}{%- endblock -%}

{%- block content -%}
<h1>Source Not Public for {{ arxiv_id.ids }}</h1>
<p>Sorry, the source for {{ arxiv_id.ids }} is not publicly available. This was the author's choice.</p>
{%- endblock -%}

browse/templates/dissemination/unavailable.html
{% extends "base/base.html" %}

{# This is the template that gets shown when the paper and version
exists, but there is no file like a PDF. This is an error condition that should
not happen but needs to be covered. #}

{%- block content -%}
<h1>file unavailable</h1>
<p>Our automated source to PDF conversion system has failed to produce PDF for the paper {{arxiv_id.ids}}.</p>
{%- endblock -%}

browse/templates/dissemination/withdrawn.html
{% extends "base/base.html" %}

{%- block title -%}Paper {{arxiv_id.ids}} withdrawn{%- endblock -%}

{%- block content -%}
<h1>This version of {{ arxiv_id.ids }} has been withdrawn and is unavailable</h1>
<p>See <a href="{{url_for('browse.abstract', arxiv_id=arxiv_id.idv)}}">abstract</a> page for more details</p>
{%- endblock -%}