browse/routes/dissemination.py
"""Routes for PDF, source and other downloads."""
from typing import Optional, Dict

from arxiv.identifier import Identifier, IdentifierException
from browse import b_add_surrogate_key
from flask import Blueprint, redirect, url_for, Response, render_template, request
from werkzeug.datastructures import Headers
from werkzeug.exceptions import InternalServerError, BadRequest

from browse.controllers import check_supplied_identifier
from browse.controllers.files.dissemination import get_html_response, get_pdf_resp, get_ps_response
from browse.services.documents import get_doc_service

blueprint = Blueprint('dissemination', __name__)


@blueprint.route("/pdf/<string:archive>/<string:arxiv_id>.pdf", methods=['GET', 'HEAD'])
@blueprint.route("/pdf/<string:arxiv_id>.pdf", methods=['GET', 'HEAD'])
def redirect_pdf(arxiv_id: str, archive=None):  # type: ignore
    """Redirect URLs with .pdf to a URL without.

    In past a redirect from /pdf/paperid to /pdf/paperid.pdf was used to cause
    the browser to download the file with the .pdf extension. This is to support
    any user who has bookmarked or saved a PDF URL with the .pdf extension in
    the past, so they will get a redirect to the "normal" PDF URL. I think we
    started using the redirect because of an ignorance of the "inline" mode of
    the content-disposition header.

    Now a content-disposition is used. It is a standard mechanism that is part
    of HTTP to provide a way for the server to specify what the file name should
    be on download.

    The content-disposition preservers the "if I download this to my computer,
    save it in a file named {paper_id}.pdf" behavior, and it does that in a
    direct and standard way. It also eliminates the redirect, which is wasteful
    and only indirectly communicates the download file name.

    """
    arxiv_id = f"{archive}/{arxiv_id}" if archive else arxiv_id
    return redirect(url_for('.pdf', arxiv_id=arxiv_id), 301)


@blueprint.route("/pdf/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/pdf/<string:arxiv_id>", methods=['GET', 'HEAD'])
def pdf(arxiv_id: str, archive=None):  # type: ignore
    """Want to handle the following patterns:

        /pdf/{archive}/{id}v{v}
        /pdf/{id}v{v}

    The dissemination service does not handle versionless
    requests. The version should be figured out in some other service
    and redirected to the CDN.

    Does a 400 if the ID is malformed or lacks a version.

    Does a 404 if the key for the ID does not exist on the bucket.
    """

    if request.query_string:  # redirect to strip off any useless query strings
        return redirect(url_for('.pdf', arxiv_id=arxiv_id, archive=archive), 301)
    return get_pdf_resp(arxiv_id, archive)


@blueprint.route("/format/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/format/<string:arxiv_id>", methods=['GET', 'HEAD'])
def format(arxiv_id: str, archive: Optional[str] = None) -> Response:
    """Get formats article."""
    arxiv_id = f"{archive}/{arxiv_id}" if archive else arxiv_id
    try:
        arxiv_identifier = Identifier(arxiv_id=arxiv_id)
    except IdentifierException:
        raise BadRequest(f"Bad paper identifier: {arxiv_id}")

    redirect_url = check_supplied_identifier(arxiv_identifier, "dissemination.format")
    if redirect_url:
        return redirect_url  # type: ignore

    abs_meta = get_doc_service().get_abs(arxiv_id)
    data = {"arxiv_id": arxiv_identifier.id, "arxiv_idv": arxiv_identifier.idv, "abs_meta": abs_meta,
            "encrypted": abs_meta.get_requested_version().source_flag.source_encrypted}

    formats = data["formats"] = abs_meta.get_requested_version().formats()

    if abs_meta.get_requested_version().source_format == "pdftex":  # ARXIVCE-3376 no ps for pdflatex
        formats = [fmt for fmt in formats if fmt != "ps"]

    for fmt in formats:
        data[fmt] = True
    # TODO DOCX doesn't seem like the url_for in the template will work correctly with the .docx?
    headers: Headers | Dict[str, str] = {}
    headers = b_add_surrogate_key(headers, ["format", f"paper-id-{arxiv_identifier.id}"])
    if arxiv_identifier.has_version:
        headers = b_add_surrogate_key(headers, [f"paper-id-{arxiv_identifier.idv}"])
    else:
        headers = b_add_surrogate_key(headers, [f"paper-id-{arxiv_identifier.id}-current"])
    return render_template("format.html", **data), 200, headers  # type: ignore


@blueprint.route("/dvi/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/dvi/<string:arxiv_id>", methods=['GET', 'HEAD'])
def dvi(arxiv_id: str) -> Response:
    """Get DVI for article."""
    raise InternalServerError(f"Not yet implemented {arxiv_id}")


@blueprint.route("/html/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/html/<string:archive>/<path:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/html/<string:arxiv_id>/", methods=['GET', 'HEAD'])
def html(arxiv_id: str, archive: Optional[str] = None):  # type: ignore
    """get html for article"""
    return get_html_response(arxiv_id, archive)


@blueprint.route("/ps/<string:archive>/<string:arxiv_id>", methods=['GET', 'HEAD'])
@blueprint.route("/ps/<string:arxiv_id>", methods=['GET', 'HEAD'])
def ps(arxiv_id: str, archive: Optional[str] = None) -> Response:
    """Get ps for article."""
    return get_ps_response(arxiv_id, archive)

browse/routes/ui.py
"""Provides the user interfaces for browse."""
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, Tuple, Union, Optional
from http import HTTPStatus as status

from arxiv.taxonomy.definitions import GROUPS
from arxiv.base import logging
from browse import b_add_surrogate_key

from flask import (
    Blueprint,
    Response,
    current_app,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from werkzeug.exceptions import BadRequest, InternalServerError, NotFound

from browse.controllers import (
    abs_page,
    archive_page,
    home_page,
    list_page,
    prevnext,
    stats_page,
    tb_page,
    catchup_page
)
from browse.controllers.openurl_cookie import make_openurl_cookie, get_openurl_page
from browse.controllers.cookies import get_cookies_page
from browse.exceptions import AbsNotFound # TODO: BASE
from browse.services.database import get_institution
from browse.controllers.year import year_page
from browse.controllers.bibtexcite import bibtex_citation
from browse.controllers.list_page import author
from browse.controllers import audio

logger = logging.getLogger(__name__)
geoip_reader = None

blueprint = Blueprint("browse", __name__, url_prefix="/")


@blueprint.app_context_processor
def inject_now() -> Dict:
    """Inject current datetime into request context."""
    return dict(request_datetime=datetime.now())


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Apply response headers to all responses."""
    """Prevent UI redress attacks."""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"

    return response


@blueprint.route("index", methods=["GET"])
@blueprint.route("/", methods=["GET"])
def home() -> Response:
    """Home page view."""
    response, code, headers = home_page.get_home_page()
    if code == status.OK:
        return render_template("home/home.html", **response), code, headers  # type: ignore

    raise InternalServerError("Unexpected error")

@blueprint.route("/favicon.ico")
@blueprint.route("/apple-touch-icon-120x120-precomposed.png")
@blueprint.route("/apple-touch-icon-120x120.png")
@blueprint.route("/apple-touch-icon-precomposed.png")
def favicon() -> Response:
    """Send favicon."""
    return send_file(Path(current_app.root_path, "static/images/icons/favicon.ico"))

@blueprint.route("abs", methods=["GET"])
def bare_abs() -> Any:
    """Check several legacy request parameters."""
    if request.args:
        if "id" in request.args:
            return abstract(request.args["id"])
        elif "archive" in request.args and "papernum" in request.args:
            return abstract(f"{request.args['archive']}/{request.args['papernum']}")
        else:
            for param in request.args:
                # singleton case, where the parameter is the value
                # e.g. /abs?<archive>/\d{7}
                if not request.args[param] and re.match(
                    r"^[a-z\-]+(\.[A-Z]{2})?\/\d{7}$", param
                ):
                    return abstract(param)

    """Return abs-specific 404."""
    raise AbsNotFound


@blueprint.route("abs/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("abs/<path:arxiv_id>", methods=["GET"])
def abstract(arxiv_id: str) -> Any:
    """Abstract (abs) page view."""
    response, code, headers = abs_page.get_abs_page(arxiv_id)
    headers=b_add_surrogate_key(headers,["abs"])
    if code == status.OK:
        if request.args and "fmt" in request.args and request.args["fmt"] == "txt":
            return Response(response["abs_meta"].raw(), mimetype="text/plain")
        return render_template("abs/abs.html", **response), code, headers
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)
    elif code == status.NOT_MODIFIED:
        return "", code, headers

    raise InternalServerError("Unexpected error")


@blueprint.route("category_taxonomy", methods=["GET"])
def category_taxonomy() -> Any:
    """Display the arXiv category taxonomy."""
    response = {"groups": GROUPS}
    return (
        render_template("category_taxonomy.html", **response),
        status.OK,
        None,
    )

@blueprint.route("catchup", methods=["GET"], endpoint="catchup_form")
def catchup_form() -> Response:
    response, code, headers = catchup_page.get_catchup_form() 
    if code == status.OK:
        return render_template("catchup_form.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("catchup/<subject>/<date>", methods=["GET"])
def catchup(subject:str, date:str) -> Response:
    response, code, headers = catchup_page.get_catchup_page(subject, date)
    headers=b_add_surrogate_key(headers,["catchup"])
    if code == status.OK:
        return render_template("catchup.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("institutional_banner", methods=["GET"])
def institutional_banner() -> Any:
    # ARXIVCE-3387, do not store the response in cache, as it is IP-specific
    response_headers = {
        "Cache-Control": "no-cache, no-store, private, max-age=0, max-stale=0",
        'Content-Type': 'application/json'}
    try:
        forwarded_ips = request.headers.getlist("X-Forwarded-For")
        if len(forwarded_ips)>0:
            ip = str(forwarded_ips[0]).split(',')[0]
            ip = ip.strip()
        elif request.remote_addr is None:
            return ("{}", status.OK, response_headers)
        else:
            ip = str(request.remote_addr)

        result = get_institution(ip)
        if result:
            return (result, status.OK, response_headers)
        else:
            return ("{}", status.OK, response_headers)
    except Exception:
        return ("", status.INTERNAL_SERVER_ERROR, response_headers)


@blueprint.route("tb/recent", methods=["GET", "POST"])
def tb_recent() -> Response:
    """Get the recent trackbacks that have been posted across the site."""
    response, code, headers = tb_page.get_recent_tb_page(request.form)

    if code == status.OK:
        return render_template("tb/recent.html", **response), code, headers  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route(
    "tb/redirect/",
    methods=["GET"],
    defaults={"trackback_id": "", "hashed_document_id": ""},
)
@blueprint.route(
    "tb/redirect/<string:trackback_id>/<string:hashed_document_id>", methods=["GET"]
)
def tb_redirect(trackback_id: str, hashed_document_id: str) -> Response:
    """Get the trackback redirect link."""
    response, code, headers = tb_page.get_tb_redirect(trackback_id, hashed_document_id)
    if code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb/<path:arxiv_id>", methods=["GET"])
def tb(arxiv_id: str) -> Response:
    """Get trackbacks associated with an article."""
    response, code, headers = tb_page.get_tb_page(arxiv_id)
    if code == status.OK:
        return render_template("tb/tb.html", **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb", strict_slashes=False)
def tb_nothing() -> Response:
    """Handle a no data trackback."""
    raise BadRequest()


@blueprint.route("prevnext", methods=["GET", "POST"])
def previous_next() -> Tuple[Dict[str, Any], int, Dict[str, Any]]:
    """Previous/Next navigation used on /abs page."""
    return prevnext.get_prevnext(
        request.args.get("id", default=""),
        request.args.get("function", default=""),
        request.args.get("context", default=""),
    )


@blueprint.route("trackback/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("trackback/<path:arxiv_id>", methods=["GET", "POST"])
def trackback(arxiv_id: str) -> Union[str, Response]:
    """Route to define new trackbacks for papers."""
    raise InternalServerError(f"Not Yet Implemented {arxiv_id}")


@blueprint.route("ct")
def clickthrough() -> Response:
    """Generate redirect for clickthrough links."""
    # 2025-01-01: Phasing out clickthrough and just supporting until all the links are gone.
    raise NotFound


@blueprint.route(
    "list", defaults={"context": "", "subcontext": ""}, methods=["GET", "POST"],
    strict_slashes=False
)
@blueprint.route("list/<context>/<subcontext>", methods=["GET", "POST"])
def list_articles(context: str, subcontext: str) -> Response:
    """
    List articles by context, month etc.

    Context might be a context or an archive; Subcontext should be
    'recent', 'new' or a string of format YYMM.
    """
    response, code, headers = list_page.get_listing(context, subcontext)
    headers=b_add_surrogate_key(headers,["list"])
    if code == status.OK:
        # TODO if it is a HEAD request we don't want to render the template
        return render_template(response["template"], **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    elif code == status.NOT_MODIFIED:
        return "", code, headers  # type: ignore
    return response, code, headers  # type: ignore


@blueprint.route("stats/main", methods=["GET"])
def main() -> Response:
    """Display the stats main page."""
    response, code, headers = stats_page.get_main_stats_page()
    return render_template("stats/main.html", **response), code, headers  # type: ignore



@blueprint.route("stats/today", methods=["GET"])
def stats_today() -> Response:
    """Display statistics about today or a day."""
    if request.args and "date" in request.args:

browse/views.py
"""Provides the user intefaces for browse."""
from typing import Union

from browse.controllers import abs, get_institution_from_request
from flask import Blueprint, render_template, request, Response, session, \
                  redirect
from arxiv import status
from arxiv.base import exceptions
from werkzeug.exceptions import InternalServerError, NotFound, HTTPException

blueprint = Blueprint('browse', __name__, url_prefix='')


@blueprint.before_request
def before_request() -> None:
    """Get instituional affiliation from session."""
    if 'institution' not in session:
        institution = get_institution_from_request()
        session['institution'] = institution


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Hook for applying response headers to all responses."""
    """Prevent UI redress attacks"""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"
    return response


@blueprint.route('/abs', methods=['GET'])
def bare_abs():
    """Return 404."""
    raise NotFound


@blueprint.route('/abs/', methods=['GET'], defaults={'arxiv_id': ''})
@blueprint.route('/abs/<path:arxiv_id>', methods=['GET', 'POST'])
def abstract(arxiv_id: str) -> Union[str, Response]:
    """Abstract (abs) page view."""
    response, code, headers = abs.get_abs_page(arxiv_id, request.args)

    if code == status.HTTP_200_OK:
        return render_template('abs/abs.html', **response), code, headers
    elif code == status.HTTP_301_MOVED_PERMANENTLY:
        return redirect(headers['Location'], code=code)
    elif code == status.HTTP_404_NOT_FOUND:
        return render_template('abs/404.html', **response), code, headers

    raise InternalServerError('Unexpected error')

browse/templates/list/author.html
{% extends "list/base.html" %}
{% import "list/list_macros.html" as list_macros with context %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<div id='content-inner'>
    <div id='dlpage'>
        <h1>{{ title }}</h1>

        {%- if orcid -%}
        <p>
            See also <a href="/help/orcid">ORCID</a> 
            {{ orcid_logo() }} <a href="{{ orcid }}">{{ orcid }}</a>.
        </p>
        {%- endif -%}
        {{ list_macros.item_list ( abstracts, '' ) }}
        {{ footer_text() }}
    </div>
</div>
{%- endblock -%}

{% macro orcid_logo() %}
<a href="http://orcid.org">
    <img src="{{ url_for('static', filename='images/icons/orcid_16x16.png') }}" alt="ORCID logo" 
        style="position:relative;bottom:-3px"/>
</a> 
{% endmacro %}

{% macro footer_text() %}
<p>
    The web address for this page and the arXiv author id for 
    {{ display_name }} is <a href="{{ auri }}">{{ auri }}</a>.  There is also
    an <a href="http://en.wikipedia.org/wiki/Atom_(standard)">Atom</a>
    feed available from <a href="{{ auri }}.atom2">{{ auri }}.atom2</a>
    (authors combined, best for most current feed readers), and 
    <a href="{{ auri }}.atom">{{ auri }}.atom</a> (authors in separate
    atom:author elements).
</p>
    
<p>
    See <a href="/help/author_identifiers">author identifier help</a>
    for more information about arXiv author identifiers, please 
    <a href="/help/contact">report</a> any problems.
</p>
{% endmacro %}

browse/templates/list/conference_item.html
{% import "list/list_macros.html" as list_macros with context %}

  {% block content %}
  {% set ids = item.arxiv_id %}

  <dt>
    <a href ="{{url_for('browse.abstract', arxiv_id=ids)}}" title="Abstract" id="{{ids}}">
      arXiv:{{ ids }}
    </a>
    {{ list_macros.dl_links( item ) }}
  </dt>
  <dd>
    <div class='meta'>
      <div class='list-title mathjax'><span class='descriptor'>Title:</span>
        {{item.title}}
      </div>
      <div class='list-authors'>
        {{- list_macros.do_author_list( item ) -}}
      </div>

      {% if item.comments %}
      <div class='list-comments mathjax'><span class='descriptor'>Comments:</span>
        {{item.comments|tex2utf|urlize|safe}}
      </div>
      {% endif %}

      {% if item.journal_ref %}
      <div class='list-journal-ref'><span class='descriptor'>Journal-ref:</span>
        {{item.journal_ref}}
      </div>
      {% endif %}

      <div class='list-subjects'><span class='descriptor'>Subjects:</span>
        {{list_macros.category_line(item)}}
      </div>

      {% if include_abstract  %}
      <p class='mathjax'>
        {{ item.abstract|tex2utf_no_symbols|abstract_lf_to_br|urlize|safe }}
      </p>
      {% endif %}
    </div>
  </dd>
  {% endblock %}

browse/templates/list/conference_proceeding.html
{% import "list/list_macros.html" as list_macros with context %}

  {% block content %}
  {% set ids = item.arxiv_id %}

  <dt>
    <a href ="{{url_for('browse.abstract', arxiv_id=ids)}}" title="Abstract" id="{{ids}}">
      arXiv:{{ ids }}
    </a>
    {{ list_macros.dl_links( item ) }}
  </dt>
  <dd>
    <div class='meta'>
      <div class='list-title mathjax'><span class='descriptor'>Title:</span>
        {{item.title}}
      </div>
      <div class='list-authors'>
        {{- list_macros.do_author_list( item ) -}}
      </div>

      {% if item.comments %}
      <div class='list-comments mathjax'><span class='descriptor'>Comments:</span>
        {{item.comments|tex2utf|urlize|safe}}
      </div>
      {% endif %}

      {% if item.journal_ref %}
      <div class='list-journal-ref'><span class='descriptor'>Journal-ref:</span>
        {{item.journal_ref}}
      </div>
      {% endif %}

      <div class='list-subjects'><span class='descriptor'>Subjects:</span>
        {{list_macros.category_line(item)}}
      </div>

      {% if include_abstract  %}
      <p class='mathjax'>
        {{ item.abstract|tex2utf_no_symbols|abstract_lf_to_br|urlize|safe }}
      </p>
      {% endif %}
    </div>
  </dd>
  {% endblock %}

browse/templates/list/list_macros.html
{%- macro page_divs() -%}
  {% if count > 0 %}
    <div class='paging'>Total of {{count}} entries {{ pages() }}
    </div>
    <div class='morefewer'>Showing up to {{shown}} entries per page:
      {{ show_link('fewer',mf_fewer) }} |
      {{ show_link('more', mf_more)  }} |
      {{ show_link('all',  mf_all)   }}
    </div>
  {% endif %}
{%- endmacro -%}


{% macro item_list(items, heading) %}
<dl id='articles'>
  {% if heading %}
    <h3>{{heading}}</h3>
  {% endif %}

  {% if items | length == 0 %}
    <p>No updates for this time period.</p>
  {% endif %}

  {% for item in items %}
    {% set article = item.article %}
    {% set ids = article.arxiv_id %}
    {% set listing_index = item.list_index %}
    <dt>
      <a name='item{{listing_index}}'>[{{listing_index}}]</a>
      <a href ="{{url_for('.abstract', arxiv_id=ids)}}" title="Abstract" id="{{ids}}">
        arXiv:{{ article.arxiv_id }}
      </a>
      {{ type_info( item ) }}
      {{ dl_links( article ) }}
    </dt>
    <dd>
      <div class='meta'>
        <div class='list-title mathjax'><span class='descriptor'>Title:</span>
          {{article.title|tex2utf}}
        </div>
        <div class='list-authors'>
          {{- do_author_list( article ) -}}
        </div>

        {% if article.comments %}
        <div class='list-comments mathjax'><span class='descriptor'>Comments:</span>
          {{article.comments|tex2utf|urlize|safe}}
        </div>
        {% endif %}

        {% if article.journal_ref %}
        <div class='list-journal-ref'><span class='descriptor'>Journal-ref:</span>
          {{article.journal_ref}}
        </div>
        {% endif %}

        <div class='list-subjects'><span class='descriptor'>Subjects:</span>
          {{category_line(article)}}
        </div>

        {% if list_type == 'new' %}
        <p class='mathjax'>
          {{ article.abstract|tex2utf_no_symbols|abstract_lf_to_br|urlize|safe }}
        </p>
        {% endif %}
      </div>
    </dd>
  {% endfor %}
</dl>
{% endmacro %}


{%- macro do_author_list(article) -%}
  {% set au_list_tup = author_links[article.arxiv_id_v] %}
  {%- if not au_list_tup or not au_list_tup[0] -%}
    (author list is unavailable)
  {%- else -%}
    {%- for part in au_list_tup[0] -%}
      {%- if part is string -%}
        {{- part|arxiv_urlize -}}
      {%- else -%}
        <a href="{{url_for_author_search(article, part[1])}}">{{part[0]}}</a>
      {%- endif -%}
    {% endfor %}
  {%- endif -%}
{%- endmacro -%}


{%- macro pages() -%}
{% if pg|length != 0 or not viewing_all %}
:
  {%- for pg in paging -%}
    {% if pg.nolink is defined %}
      <span>{{pg.nolink}}</span>
    {% else %}
      <a href={{pg.url}}>{{pg.txt}}</a>
    {% endif %}
  {% endfor %}
{% endif %}
{%- endmacro -%}


{%- macro show_link( txt, to_show ) %}
  {% if to_show %}
    <a href={{url_for('.list_articles',context=context, subcontext=subcontext, skip=skipn, show=to_show)}} rel="nofollow">
      {{txt}}</a>
  {% else %}
    <span style="color: #454545">{{txt}}</span>
  {% endif %}
{%- endmacro -%}

{%- macro dl_links( article ) -%}
  {% set id = article.arxiv_id %}
  {% set downloads = downloads[ article.arxiv_id_v ] %}
  {% set latexml_link = latexml.get(article.arxiv_id_v) %}
  [<a href="{{url_for('dissemination.pdf', arxiv_id=id)}}" title="Download PDF" id="pdf-{{id}}" aria-labelledby="pdf-{{id}}">pdf</a>
  {%- if latexml_link -%}
    , <a href="{{ latexml_link }}" title="View HTML" id="html-{{id}}" aria-labelledby="html-{{id}}" rel="noopener noreferrer" target="_blank">html</a>
  {%- endif -%}
  {%- if 'other' in downloads -%}
    , <a href="{{url_for('dissemination.format', arxiv_id=id)}}" title="Other formats" id="oth-{{id}}" aria-labelledby="oth-{{id}}">other</a>
  {%- endif -%}
  ]
{%- endmacro -%}

{% macro type_info( item ) %}
  {% if item['listingType'] == 'cross' %}
    (cross-list from {{item['primary']}})
  {% endif %}
  {% if item['listingType'] == 'rep' %}
    (replaced)
  {% endif %}
{% endmacro %}


{%- macro category_line(article) -%}
  <span class="primary-subject">{{- article.primary_category.display() -}}</span>
  {%- if article.secondary_categories -%}
    {%- for category in article.display_secondaries() -%}
        ; {{ category }}
    {%- endfor -%}
  {%- endif -%}
{%- endmacro -%}

browse/templates/list/month.html
{%- extends "list/base.html" -%}

{% block list_index %}

<h2>Authors and titles for {{pubmonth.strftime('%B %Y')}} </h2>
{% endblock %}

browse/templates/list/recent.html
{%- extends "list/base.html" -%}

{%- block list_index -%}
  <h2>Authors and titles for recent submissions</h2>
  <ul>
    {% set cumulative = namespace(total=0) %}
    {%- for pdate in pubdates -%}
      {%- set skipfordate = cumulative.total -%}
      {%- set cumulative.total = cumulative.total + pdate[1] -%}
      <li>
        <a href="{{url_for('browse.list_articles', context=context, subcontext='recent', skip=skipfordate, show=shown ) }}">
          {{ pdate[0].strftime('%a, %-d %b %Y') }}
        </a>
      </li>
    {%- endfor -%}
  </ul>
  <p>See today's <a id="new-{{ context }}" aria-labelledby="new-{{ context }}" href="/list/{{ context }}/new">new</a> changes</p>
{%- endblock -%}

{% block items %}
  {% for sec in sub_sections_for_types %}
    {%if sec.visible%}
      {{ list_macros.item_list(sec.items, sec.heading) }}
    {% endif %}
  {% endfor %}
{% endblock %}

browse/templates/list/year.html
{%- extends "list/base.html" -%}

{% block list_index %}

<h2>Authors and titles for {{pubmonth.strftime('%Y')}} </h2>
{% endblock %}