browse/routes/ui.py
"""Provides the user interfaces for browse."""
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, Tuple, Union, Optional
from http import HTTPStatus as status

from arxiv.taxonomy.definitions import GROUPS
from arxiv.base import logging
from browse import b_add_surrogate_key

from flask import (
    Blueprint,
    Response,
    current_app,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from werkzeug.exceptions import BadRequest, InternalServerError, NotFound

from browse.controllers import (
    abs_page,
    archive_page,
    home_page,
    list_page,
    prevnext,
    stats_page,
    tb_page,
    catchup_page
)
from browse.controllers.openurl_cookie import make_openurl_cookie, get_openurl_page
from browse.controllers.cookies import get_cookies_page
from browse.exceptions import AbsNotFound # TODO: BASE
from browse.services.database import get_institution
from browse.controllers.year import year_page
from browse.controllers.bibtexcite import bibtex_citation
from browse.controllers.list_page import author
from browse.controllers import audio

logger = logging.getLogger(__name__)
geoip_reader = None

blueprint = Blueprint("browse", __name__, url_prefix="/")


@blueprint.app_context_processor
def inject_now() -> Dict:
    """Inject current datetime into request context."""
    return dict(request_datetime=datetime.now())


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Apply response headers to all responses."""
    """Prevent UI redress attacks."""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"

    return response


@blueprint.route("index", methods=["GET"])
@blueprint.route("/", methods=["GET"])
def home() -> Response:
    """Home page view."""
    response, code, headers = home_page.get_home_page()
    if code == status.OK:
        return render_template("home/home.html", **response), code, headers  # type: ignore

    raise InternalServerError("Unexpected error")

@blueprint.route("/favicon.ico")
@blueprint.route("/apple-touch-icon-120x120-precomposed.png")
@blueprint.route("/apple-touch-icon-120x120.png")
@blueprint.route("/apple-touch-icon-precomposed.png")
def favicon() -> Response:
    """Send favicon."""
    return send_file(Path(current_app.root_path, "static/images/icons/favicon.ico"))

@blueprint.route("abs", methods=["GET"])
def bare_abs() -> Any:
    """Check several legacy request parameters."""
    if request.args:
        if "id" in request.args:
            return abstract(request.args["id"])
        elif "archive" in request.args and "papernum" in request.args:
            return abstract(f"{request.args['archive']}/{request.args['papernum']}")
        else:
            for param in request.args:
                # singleton case, where the parameter is the value
                # e.g. /abs?<archive>/\d{7}
                if not request.args[param] and re.match(
                    r"^[a-z\-]+(\.[A-Z]{2})?\/\d{7}$", param
                ):
                    return abstract(param)

    """Return abs-specific 404."""
    raise AbsNotFound


@blueprint.route("abs/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("abs/<path:arxiv_id>", methods=["GET"])
def abstract(arxiv_id: str) -> Any:
    """Abstract (abs) page view."""
    response, code, headers = abs_page.get_abs_page(arxiv_id)
    headers=b_add_surrogate_key(headers,["abs"])
    if code == status.OK:
        if request.args and "fmt" in request.args and request.args["fmt"] == "txt":
            return Response(response["abs_meta"].raw(), mimetype="text/plain")
        return render_template("abs/abs.html", **response), code, headers
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)
    elif code == status.NOT_MODIFIED:
        return "", code, headers

    raise InternalServerError("Unexpected error")


@blueprint.route("category_taxonomy", methods=["GET"])
def category_taxonomy() -> Any:
    """Display the arXiv category taxonomy."""
    response = {"groups": GROUPS}
    return (
        render_template("category_taxonomy.html", **response),
        status.OK,
        None,
    )

@blueprint.route("catchup", methods=["GET"], endpoint="catchup_form")
def catchup_form() -> Response:
    response, code, headers = catchup_page.get_catchup_form() 
    if code == status.OK:
        return render_template("catchup_form.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("catchup/<subject>/<date>", methods=["GET"])
def catchup(subject:str, date:str) -> Response:
    response, code, headers = catchup_page.get_catchup_page(subject, date)
    headers=b_add_surrogate_key(headers,["catchup"])
    if code == status.OK:
        return render_template("catchup.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("institutional_banner", methods=["GET"])
def institutional_banner() -> Any:
    # ARXIVCE-3387, do not store the response in cache, as it is IP-specific
    response_headers = {
        "Cache-Control": "no-cache, no-store, private, max-age=0, max-stale=0",
        'Content-Type': 'application/json'}
    try:
        forwarded_ips = request.headers.getlist("X-Forwarded-For")
        if len(forwarded_ips)>0:
            ip = str(forwarded_ips[0]).split(',')[0]
            ip = ip.strip()
        elif request.remote_addr is None:
            return ("{}", status.OK, response_headers)
        else:
            ip = str(request.remote_addr)

        result = get_institution(ip)
        if result:
            return (result, status.OK, response_headers)
        else:
            return ("{}", status.OK, response_headers)
    except Exception:
        return ("", status.INTERNAL_SERVER_ERROR, response_headers)


@blueprint.route("tb/recent", methods=["GET", "POST"])
def tb_recent() -> Response:
    """Get the recent trackbacks that have been posted across the site."""
    response, code, headers = tb_page.get_recent_tb_page(request.form)

    if code == status.OK:
        return render_template("tb/recent.html", **response), code, headers  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route(
    "tb/redirect/",
    methods=["GET"],
    defaults={"trackback_id": "", "hashed_document_id": ""},
)
@blueprint.route(
    "tb/redirect/<string:trackback_id>/<string:hashed_document_id>", methods=["GET"]
)
def tb_redirect(trackback_id: str, hashed_document_id: str) -> Response:
    """Get the trackback redirect link."""
    response, code, headers = tb_page.get_tb_redirect(trackback_id, hashed_document_id)
    if code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb/<path:arxiv_id>", methods=["GET"])
def tb(arxiv_id: str) -> Response:
    """Get trackbacks associated with an article."""
    response, code, headers = tb_page.get_tb_page(arxiv_id)
    if code == status.OK:
        return render_template("tb/tb.html", **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb", strict_slashes=False)
def tb_nothing() -> Response:
    """Handle a no data trackback."""
    raise BadRequest()


@blueprint.route("prevnext", methods=["GET", "POST"])
def previous_next() -> Tuple[Dict[str, Any], int, Dict[str, Any]]:
    """Previous/Next navigation used on /abs page."""
    return prevnext.get_prevnext(
        request.args.get("id", default=""),
        request.args.get("function", default=""),
        request.args.get("context", default=""),
    )


@blueprint.route("trackback/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("trackback/<path:arxiv_id>", methods=["GET", "POST"])
def trackback(arxiv_id: str) -> Union[str, Response]:
    """Route to define new trackbacks for papers."""
    raise InternalServerError(f"Not Yet Implemented {arxiv_id}")


@blueprint.route("ct")
def clickthrough() -> Response:
    """Generate redirect for clickthrough links."""
    # 2025-01-01: Phasing out clickthrough and just supporting until all the links are gone.
    raise NotFound


@blueprint.route(
    "list", defaults={"context": "", "subcontext": ""}, methods=["GET", "POST"],
    strict_slashes=False
)
@blueprint.route("list/<context>/<subcontext>", methods=["GET", "POST"])
def list_articles(context: str, subcontext: str) -> Response:
    """
    List articles by context, month etc.

    Context might be a context or an archive; Subcontext should be
    'recent', 'new' or a string of format YYMM.
    """
    response, code, headers = list_page.get_listing(context, subcontext)
    headers=b_add_surrogate_key(headers,["list"])
    if code == status.OK:
        # TODO if it is a HEAD request we don't want to render the template
        return render_template(response["template"], **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    elif code == status.NOT_MODIFIED:
        return "", code, headers  # type: ignore
    return response, code, headers  # type: ignore


@blueprint.route("stats/main", methods=["GET"])
def main() -> Response:
    """Display the stats main page."""
    response, code, headers = stats_page.get_main_stats_page()
    return render_template("stats/main.html", **response), code, headers  # type: ignore



@blueprint.route("stats/today", methods=["GET"])
def stats_today() -> Response:
    """Display statistics about today or a day."""
    if request.args and "date" in request.args:

browse/templates/tb/base.html
{%- extends "base.html" -%}
{# Do not show login status on these pages for now, per classic #}

{% block head %}
  {{ super() -}}
  <script src="{{ url_for('static', filename='js/mathjaxToggle.min.js') }}" type="text/javascript"></script>
  <style type="text/css">
    p.blog { margin-bottom: 0; }
    ul.blog { list-style-type: none; margin-top: 0; font-size: 90%; }
  </style>
{% endblock head %}

{%- block content %}
  <div style="font-size: smaller; margin-top: 2em;">
  <p>By sending a <a href="{{ url_for('help_trackback') }}">trackback</a>, you can notify
  arXiv.org that you have created a web page that references a paper. Popular
  blogging software supports trackback:  you can send us a trackback about this
  paper by giving your software the following <em>trackback URL:</em></p>
  <blockquote>https://arxiv.org/trackback/{arXiv_id}</blockquote>
  <p>Some blogging software supports <em>trackback autodiscovery</em> -- in this
  case,  your software will automatically send a trackback as soon as your
  create a link to our abstract page.  See our
  <a href="{{ url_for('help_trackback') }}">trackback help page</a> for more information.</p>
  </div>
  <script type="text/javascript" language="javascript">mathjaxToggle();</script>
{% endblock content %}

browse/templates/tb/macros.html
{%- macro generate_trackback_link(trackback, include_posted_date=True) -%}
<h3 class="trackback-title">
  <a class="mathjax" rel="external nofollow" href="{{ url_for('browse.tb_redirect', trackback_id=trackback.trackback_id, hashed_document_id=trackback.hashed_document_id) }}">
  {{- trackback.title|entity_to_utf|truncate(150) }}</a>
</h3>
<p class="trackback-source">
  [
  {%- if trackback.blog_name %}
    {{ trackback.blog_name|trim|entity_to_utf|truncate(50) -}} @
  {% endif -%}
  {%- if trackback.has_valid_url %}
    <a class="mathjax" rel="external nofollow" href="{{ url_for('browse.tb_redirect', trackback_id=trackback.trackback_id, hashed_document_id=trackback.hashed_document_id) }}">{{ trackback.display_url|truncate(30,False) }}</a>
  {% else %}
    INVALID-URL
  {% endif -%}
  ]
  {%- if include_posted_date %}
    <small>trackback posted {{ trackback.posted_datetime.strftime('%a, %-d %b %Y %H:%M:%S %Z') }}</small>
  {% endif %}
</p>
{%- endmacro -%}

browse/templates/tb/recent.html
{%- extends "tb/base.html" -%}
{%- from 'tb/macros.html' import generate_trackback_link -%}
{%- import 'base/macros.html' as base_macros -%}

{% block title %}Recent Trackbacks{% endblock %}
{% block header_h1 %}<h1><a href="{{ url_for('.home') }}">{{ config['BROWSE_SITE_LABEL'] }}</a> &gt; recent trackbacks</h1>{% endblock %}

{%- block content %}
  <div class="columns">
    <div class="column">
      <h1>arXiv<br><span style="color:grey;">Recent Trackbacks</span></h1>
      <p>Trackbacks indicate external web sites that link to articles in arXiv.org.
        Trackbacks do not reflect the opinion of arXiv.org and may not reflect the opinions of that article's authors.</p>
    </div>
    <div class="column guide is-three-fifths">
      <h2 style="margin:0;">Trackback guide</h2>
      {{ super() }}
    </div>
  </div>


  {% if recent_trackback_pings -%}
  <div id="{{ list_name }}_list" class="large-data-list bold-divided-list trackback-styles">
    <form action="{{ url_for('browse.tb_recent') }}" method="post" class="form-trackbacks">
      <label for="select_trackbacks"><span class="is-hidden-mobile">Number of trackbacks to </span>view:</label>
      <select name="views" id="select_trackbacks">
        {%- for option in trackback_count_options -%}
        <option value="{{ option }}"{% if max_trackbacks == option %} selected="selected"{% endif %}>last {{ option }}</option>
        {%- endfor -%}
      </select>
      <input type="submit" name="recent_trackbacks_refresh" value="Refresh" class="button is-link is-small is-outline">
    </form>

    {%- set ns = namespace(cur_tb_ymd='', cur_tb_url='') -%}
    {%- for recent_tb in recent_trackback_pings -%}
    <div class="columns">
      {%- set this_tb_ymd = recent_tb[0].posted_datetime.strftime('%B %-d, %Y') -%}
      {%- set this_tb_url = recent_tb[0].url -%}

        {%- if this_tb_ymd != ns.cur_tb_ymd -%}
        {%- endif -%}

        <div class="column is-one-fifth">
          {%- if this_tb_ymd != ns.cur_tb_ymd -%}
          {%- set ns.cur_tb_ymd = this_tb_ymd -%}
            <h3 class="bold-divided-header">{{ this_tb_ymd }}</h3>
          {%- endif -%}
        </div>

        {%- if this_tb_url != ns.cur_tb_url -%}
          {%- set ns.cur_tb_url = this_tb_url -%}
          <div class="column bold-divided-column">
            <p>{{- generate_trackback_link(recent_tb[0], include_posted_date=False) }} links the following articles:</p>
            <ul>
              {%- for article in article_map[this_tb_url] -%}
              <li><span class="mathjax">{{ article[1]|tex2utf }}<span> [<a class="mathjax" href="{{ url_for('.abstract', arxiv_id=article[0]) }}">{{ article[0] }}</a>]</li>
              {%- endfor -%}
            </ul>
          </div>
        {%- endif -%}
    </div>
    {%- endfor -%}

  </div>
  {%- endif %}



{% endblock content %}

browse/templates/tb/tb.html
{%- extends "tb/base.html" -%}
{%- from 'abs/author_links.html' import display_authors_with_links -%}
{%- import 'base/macros.html' as base_macros -%}
{%- from 'tb/macros.html' import generate_trackback_link -%}

{% block title %}Article Trackbacks{% endblock %}
{% block header_h1 %}<h1><a href="/">{{ config['BROWSE_SITE_LABEL'] }}</a> &gt; article trackbacks</h1>{% endblock %}
{# Disable login on this page for now, per classic #}
{% block login_link %}{% endblock %}
{% set list_name = 'metadata' %}

{%- block content %}
  <div class="columns">
    <div class="column">
      <h1>arXiv<br><span style="color:grey;">Trackbacks</span></h1>
      <p>Trackbacks indicate external web sites that link to articles in arXiv.org.
        Trackbacks do not reflect the opinion of arXiv.org and may not reflect the opinions of that article's authors.</p>
    </div>
    <div class="column guide is-three-fifths">
      <h2 style="margin:0;">Trackback guide</h2>
      {{ super() }}
    </div>
  </div>

  <div class="large-data-list bold-divided-list trackback-styles">
  {% if trackback_pings %}
    <h2 class="trackback-heading">Trackbacks for <a href="{{ url_for('.abstract', arxiv_id=arxiv_identifier.id) }}">{{ arxiv_identifier.id }}</a></h2>
    {% for tb in trackback_pings %}
      {{- generate_trackback_link(tb) -}}
    {% endfor %}
  </div>
  <div id="{{ list_name }}_list" class="large-data-list trackback-styles">
    <h4 class="accordion-head">Click to view metadata for {{ arxiv_identifier.id }}</h4>
    <div class="accordion-body"><blockquote>
      {#- abstract field is deliberately suppressed in call to abs macro. -#}
      {%- if abs_meta -%}
      {{ base_macros.abs(
        abs_meta.arxiv_identifier.id,
        abs_meta.title,
        display_authors_with_links(abs_meta, author_links),
        '',
        abs_meta.get_datetime_of_version(abs_meta.version),
        abs_meta.primary_category,
        comments = abs_meta.comments,
        msc_class = abs_meta.msc_class,
        acm_class = abs_meta.acm_class,
        journal_ref = abs_meta.journal_ref,
        doi = abs_meta.doi,
        report_num = abs_meta.report_num,
        version = abs_meta.version,
        submission_history = abs_meta.version_history,
        secondary_categories = abs_meta.get_secondaries()) }}
    </blockquote></div>
    {%- endif -%}
  {% else %}
  <p><em>There are no trackback pings recorded for <a href="{{ url_for('.abstract', arxiv_id=arxiv_identifier.id) }}">{{ arxiv_identifier.id }}</a>.</em></p>
  {% endif %}
  </div>
<script type="text/javascript">
// vanilla accordion script
var jsaccordion = {
  init : function (target) {
  // initialize the accordion
    var headers = document.querySelectorAll("#" + target + " .accordion-head");
    if (headers.length > 0) { for (var head of headers) {
      head.addEventListener("click", jsaccordion.select);
    }}
  },
  select : function () {
  // fired when user clicks on a header
    var contents = this.nextElementSibling;
    contents.classList.toggle("open");
    var contents = this;
    contents.classList.toggle("open");
  }
};
// runs on page load. Dont forget to set variable 'list_name' on your page.
window.addEventListener('load', function(){
  jsaccordion.init("{{ list_name }}_list");
});
</script>
{% endblock content %}