browse/controllers/author.py
from typing import Optional, Dict, Any, Tuple, List
from urllib.parse import unquote
import re

from flask import request
from werkzeug.exceptions import BadRequest

from ..domain.listing import ListingItem
from ..services.database import (
    get_user_id_by_author_id, 
    get_user_id_by_orcid,
    get_user_display_name,
    get_orcid_by_user_id,
    get_articles_for_author
)
from ..services.document import metadata


ORCID_URI_PREFIX = 'https://orcid.org'
ORCID_RE = re.compile(r'^(\d{4}\-\d{4}\-\d{4}-\d{3}[\dX])$')

def _get_user_id (raw_id: str) -> Tuple[Optional[int], bool]:
    id = unquote(raw_id) # Check if flask does this automatically
    if ORCID_RE.match(id):
        return get_user_id_by_orcid(id), True
    return get_user_id_by_author_id(id), False

def _get_orcid_uri (user_id: int) -> Optional[str]:
    orcid = get_orcid_by_user_id(user_id)
    if orcid is not None:
        return f'{ORCID_URI_PREFIX}/{orcid}'
    return None

def get_a_page (id: str, ext: str):
    user_id, is_orcid = _get_user_id(id)
    if user_id is None:
        raise BadRequest (f'Author {id} not found')
    
    response_data: Dict[str, Any] = {}

    response_data['display_name'] = get_user_display_name(user_id)
    response_data['auri'] = f'{request.url_root}{id}'
    if is_orcid:
        response_data['orcid'] = f'{ORCID_URI_PREFIX}/{unquote(id)}'
    else:
        response_data['orcid'] = _get_orcid_uri (user_id)
    response_data['title'] = f'{response_data["display_name"]}\'s articles on arXiv'

    listings = get_articles_for_author(user_id)
    for i, item in enumerate(listings):
        item['article'] = metadata.get_abs(item['id'])  # type: ignore
        item['list_index'] = i + 1

    response_data['abstracts'] = listings

    return response_data, 200, {}

browse/routes/src.py
"""Routes for serving the source of articles. /src /e-prints and ancillary."""
import logging
from typing import Optional

from arxiv.identifier import Identifier, IdentifierException
from browse import b_add_surrogate_key

from browse.controllers.files.dissemination import get_src_resp
from browse.controllers.files.ancillary_files import get_extracted_src_file_resp
from browse.services.dissemination import get_article_store
from browse.services.documents import get_doc_service
from flask import Blueprint, Response, make_response, render_template
from opentelemetry import trace

logger = logging.getLogger(__file__)
logger.setLevel(logging.INFO)

blueprint = Blueprint('src', __name__)

tracer = trace.get_tracer(__name__)


@blueprint.route("/src/<path:arxiv_id>/anc")
def anc_listing(arxiv_id: str):  #type: ignore
    """Serves listing of ancillary files for a paper."""
    data: dict = {}
    docmeta = get_doc_service().get_abs(arxiv_id)
    data['abs_meta'] = docmeta
    data['arxiv_id'] = docmeta.arxiv_identifier
    data['anc_file_list'] = get_article_store().get_ancillary_files(docmeta)

    if data['anc_file_list']:
        resp=make_response(render_template("src/listing.html", **data))
        _src_surrogate_keys(resp, arxiv_id, True)
        return resp
    else:
        resp=make_response(render_template("src/listing_none.html", **data))
        _src_surrogate_keys(resp, arxiv_id, True)
        resp.status_code=404
        return resp


@blueprint.route("/src/<path:arxiv_id>/anc/<path:file_path>")
def anc(arxiv_id: str, file_path:str):  # type: ignore
    """Serves ancillary files or show html page of ancillary files

    Returns just the specified file within the source package. Has
    meaning only for .tar.gz packages and will most frequently be used to access
    ancillary files such as /src/anc/some_file

    ex https://arxiv.org/src/1911.08265v1/anc
    ex https://arxiv.org/src/1911.08265v1/anc/pseudocode.py
    """
    resp=get_extracted_src_file_resp(arxiv_id, f"anc/{file_path}", 'anc')
    _src_surrogate_keys(resp, arxiv_id, True)
    return resp


@blueprint.route("/e-print/<string:arxiv_id_str>")
@blueprint.route("/e-print/<string:archive>/<string:arxiv_id_str>")
@blueprint.route("/src/<string:arxiv_id_str>")
@blueprint.route("/src/<string:archive>/<string:arxiv_id_str>")
def src(arxiv_id_str: str, archive: Optional[str]=None):  # type: ignore
    """Serves the source of a requested paper.

    This serves it in the original format submitted. Before 2024 it would .tar up
    single file submissions.

    The e-print path serves the source of a requested paper as original format submitted and
    form that we store it (.tar.gz, .pdf, etc.). It is used to support the mirrors.
    Before 2024 /src behavior was different than /e-print.
     """
    resp=get_src_resp(arxiv_id_str, archive) #always adds a verion onto the id
    _src_surrogate_keys(resp, arxiv_id_str)
    return resp


def _src_surrogate_keys(resp: Response, arxiv_id_str: str, anc:bool=False) -> None:
    resp.headers=b_add_surrogate_key(resp.headers,["src"])
    if _check_id_for_version(arxiv_id_str):
        resp.headers=b_add_surrogate_key(resp.headers,[f"src-{arxiv_id_str}",
                                                     f"paper-id-{arxiv_id_str}"])
    else:
        resp.headers=b_add_surrogate_key(resp.headers,[f"src-{arxiv_id_str}-current",
                                                     f"paper-id-{arxiv_id_str}-current"])

    if anc:
        resp.headers=b_add_surrogate_key(resp.headers,["anc"])
        if _check_id_for_version(arxiv_id_str):
            resp.headers=b_add_surrogate_key(resp.headers,[f"anc-{arxiv_id_str}"])
        else:
            resp.headers=b_add_surrogate_key(resp.headers,[f"anc-{arxiv_id_str}-current"])


def _check_id_for_version(arxiv_id_str:str) -> bool:
    """returns true if the url was asking for a specific paper version, false otherwise"""
    try:
        arxiv_id= Identifier(arxiv_id_str)
        if arxiv_id.has_version:
            return True
        else:
            return False
    except IdentifierException:
        return False

browse/routes/ui.py
"""Provides the user interfaces for browse."""
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, Tuple, Union, Optional
from http import HTTPStatus as status

from arxiv.taxonomy.definitions import GROUPS
from arxiv.base import logging
from browse import b_add_surrogate_key

from flask import (
    Blueprint,
    Response,
    current_app,
    make_response,
    redirect,
    render_template,
    request,
    send_file,
    url_for,
)
from werkzeug.exceptions import BadRequest, InternalServerError, NotFound

from browse.controllers import (
    abs_page,
    archive_page,
    home_page,
    list_page,
    prevnext,
    stats_page,
    tb_page,
    catchup_page
)
from browse.controllers.openurl_cookie import make_openurl_cookie, get_openurl_page
from browse.controllers.cookies import get_cookies_page
from browse.exceptions import AbsNotFound # TODO: BASE
from browse.services.database import get_institution
from browse.controllers.year import year_page
from browse.controllers.bibtexcite import bibtex_citation
from browse.controllers.list_page import author
from browse.controllers import audio

logger = logging.getLogger(__name__)
geoip_reader = None

blueprint = Blueprint("browse", __name__, url_prefix="/")


@blueprint.app_context_processor
def inject_now() -> Dict:
    """Inject current datetime into request context."""
    return dict(request_datetime=datetime.now())


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Apply response headers to all responses."""
    """Prevent UI redress attacks."""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"

    return response


@blueprint.route("index", methods=["GET"])
@blueprint.route("/", methods=["GET"])
def home() -> Response:
    """Home page view."""
    response, code, headers = home_page.get_home_page()
    if code == status.OK:
        return render_template("home/home.html", **response), code, headers  # type: ignore

    raise InternalServerError("Unexpected error")

@blueprint.route("/favicon.ico")
@blueprint.route("/apple-touch-icon-120x120-precomposed.png")
@blueprint.route("/apple-touch-icon-120x120.png")
@blueprint.route("/apple-touch-icon-precomposed.png")
def favicon() -> Response:
    """Send favicon."""
    return send_file(Path(current_app.root_path, "static/images/icons/favicon.ico"))

@blueprint.route("abs", methods=["GET"])
def bare_abs() -> Any:
    """Check several legacy request parameters."""
    if request.args:
        if "id" in request.args:
            return abstract(request.args["id"])
        elif "archive" in request.args and "papernum" in request.args:
            return abstract(f"{request.args['archive']}/{request.args['papernum']}")
        else:
            for param in request.args:
                # singleton case, where the parameter is the value
                # e.g. /abs?<archive>/\d{7}
                if not request.args[param] and re.match(
                    r"^[a-z\-]+(\.[A-Z]{2})?\/\d{7}$", param
                ):
                    return abstract(param)

    """Return abs-specific 404."""
    raise AbsNotFound


@blueprint.route("abs/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("abs/<path:arxiv_id>", methods=["GET"])
def abstract(arxiv_id: str) -> Any:
    """Abstract (abs) page view."""
    response, code, headers = abs_page.get_abs_page(arxiv_id)
    headers=b_add_surrogate_key(headers,["abs"])
    if code == status.OK:
        if request.args and "fmt" in request.args and request.args["fmt"] == "txt":
            return Response(response["abs_meta"].raw(), mimetype="text/plain")
        return render_template("abs/abs.html", **response), code, headers
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)
    elif code == status.NOT_MODIFIED:
        return "", code, headers

    raise InternalServerError("Unexpected error")


@blueprint.route("category_taxonomy", methods=["GET"])
def category_taxonomy() -> Any:
    """Display the arXiv category taxonomy."""
    response = {"groups": GROUPS}
    return (
        render_template("category_taxonomy.html", **response),
        status.OK,
        None,
    )

@blueprint.route("catchup", methods=["GET"], endpoint="catchup_form")
def catchup_form() -> Response:
    response, code, headers = catchup_page.get_catchup_form() 
    if code == status.OK:
        return render_template("catchup_form.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("catchup/<subject>/<date>", methods=["GET"])
def catchup(subject:str, date:str) -> Response:
    response, code, headers = catchup_page.get_catchup_page(subject, date)
    headers=b_add_surrogate_key(headers,["catchup"])
    if code == status.OK:
        return render_template("catchup.html", **response), code, headers  # type: ignore
    return response, code, headers  # type: ignore

@blueprint.route("institutional_banner", methods=["GET"])
def institutional_banner() -> Any:
    # ARXIVCE-3387, do not store the response in cache, as it is IP-specific
    response_headers = {
        "Cache-Control": "no-cache, no-store, private, max-age=0, max-stale=0",
        'Content-Type': 'application/json'}
    try:
        forwarded_ips = request.headers.getlist("X-Forwarded-For")
        if len(forwarded_ips)>0:
            ip = str(forwarded_ips[0]).split(',')[0]
            ip = ip.strip()
        elif request.remote_addr is None:
            return ("{}", status.OK, response_headers)
        else:
            ip = str(request.remote_addr)

        result = get_institution(ip)
        if result:
            return (result, status.OK, response_headers)
        else:
            return ("{}", status.OK, response_headers)
    except Exception:
        return ("", status.INTERNAL_SERVER_ERROR, response_headers)


@blueprint.route("tb/recent", methods=["GET", "POST"])
def tb_recent() -> Response:
    """Get the recent trackbacks that have been posted across the site."""
    response, code, headers = tb_page.get_recent_tb_page(request.form)

    if code == status.OK:
        return render_template("tb/recent.html", **response), code, headers  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route(
    "tb/redirect/",
    methods=["GET"],
    defaults={"trackback_id": "", "hashed_document_id": ""},
)
@blueprint.route(
    "tb/redirect/<string:trackback_id>/<string:hashed_document_id>", methods=["GET"]
)
def tb_redirect(trackback_id: str, hashed_document_id: str) -> Response:
    """Get the trackback redirect link."""
    response, code, headers = tb_page.get_tb_redirect(trackback_id, hashed_document_id)
    if code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb/<path:arxiv_id>", methods=["GET"])
def tb(arxiv_id: str) -> Response:
    """Get trackbacks associated with an article."""
    response, code, headers = tb_page.get_tb_page(arxiv_id)
    if code == status.OK:
        return render_template("tb/tb.html", **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    raise InternalServerError("Unexpected error")


@blueprint.route("tb", strict_slashes=False)
def tb_nothing() -> Response:
    """Handle a no data trackback."""
    raise BadRequest()


@blueprint.route("prevnext", methods=["GET", "POST"])
def previous_next() -> Tuple[Dict[str, Any], int, Dict[str, Any]]:
    """Previous/Next navigation used on /abs page."""
    return prevnext.get_prevnext(
        request.args.get("id", default=""),
        request.args.get("function", default=""),
        request.args.get("context", default=""),
    )


@blueprint.route("trackback/", methods=["GET"], defaults={"arxiv_id": ""})
@blueprint.route("trackback/<path:arxiv_id>", methods=["GET", "POST"])
def trackback(arxiv_id: str) -> Union[str, Response]:
    """Route to define new trackbacks for papers."""
    raise InternalServerError(f"Not Yet Implemented {arxiv_id}")


@blueprint.route("ct")
def clickthrough() -> Response:
    """Generate redirect for clickthrough links."""
    # 2025-01-01: Phasing out clickthrough and just supporting until all the links are gone.
    raise NotFound


@blueprint.route(
    "list", defaults={"context": "", "subcontext": ""}, methods=["GET", "POST"],
    strict_slashes=False
)
@blueprint.route("list/<context>/<subcontext>", methods=["GET", "POST"])
def list_articles(context: str, subcontext: str) -> Response:
    """
    List articles by context, month etc.

    Context might be a context or an archive; Subcontext should be
    'recent', 'new' or a string of format YYMM.
    """
    response, code, headers = list_page.get_listing(context, subcontext)
    headers=b_add_surrogate_key(headers,["list"])
    if code == status.OK:
        # TODO if it is a HEAD request we don't want to render the template
        return render_template(response["template"], **response), code, headers  # type: ignore
    elif code == status.MOVED_PERMANENTLY:
        return redirect(headers["Location"], code=code)  # type: ignore
    elif code == status.NOT_MODIFIED:
        return "", code, headers  # type: ignore
    return response, code, headers  # type: ignore


@blueprint.route("stats/main", methods=["GET"])
def main() -> Response:
    """Display the stats main page."""
    response, code, headers = stats_page.get_main_stats_page()
    return render_template("stats/main.html", **response), code, headers  # type: ignore



@blueprint.route("stats/today", methods=["GET"])
def stats_today() -> Response:
    """Display statistics about today or a day."""
    if request.args and "date" in request.args:

browse/views.py
"""Provides the user intefaces for browse."""
from typing import Union

from browse.controllers import abs, get_institution_from_request
from flask import Blueprint, render_template, request, Response, session, \
                  redirect
from arxiv import status
from arxiv.base import exceptions
from werkzeug.exceptions import InternalServerError, NotFound, HTTPException

blueprint = Blueprint('browse', __name__, url_prefix='')


@blueprint.before_request
def before_request() -> None:
    """Get instituional affiliation from session."""
    if 'institution' not in session:
        institution = get_institution_from_request()
        session['institution'] = institution


@blueprint.after_request
def apply_response_headers(response: Response) -> Response:
    """Hook for applying response headers to all responses."""
    """Prevent UI redress attacks"""
    response.headers["Content-Security-Policy"] = "frame-ancestors 'none'"
    response.headers["X-Frame-Options"] = "SAMEORIGIN"
    return response


@blueprint.route('/abs', methods=['GET'])
def bare_abs():
    """Return 404."""
    raise NotFound


@blueprint.route('/abs/', methods=['GET'], defaults={'arxiv_id': ''})
@blueprint.route('/abs/<path:arxiv_id>', methods=['GET', 'POST'])
def abstract(arxiv_id: str) -> Union[str, Response]:
    """Abstract (abs) page view."""
    response, code, headers = abs.get_abs_page(arxiv_id, request.args)

    if code == status.HTTP_200_OK:
        return render_template('abs/abs.html', **response), code, headers
    elif code == status.HTTP_301_MOVED_PERMANENTLY:
        return redirect(headers['Location'], code=code)
    elif code == status.HTTP_404_NOT_FOUND:
        return render_template('abs/404.html', **response), code, headers

    raise InternalServerError('Unexpected error')

browse/templates/alert_macro.html
{%- macro alert(title, content) -%}
<div class="alert" role="status" aria-label="{{title}}">
    <button aria-label="Dismiss alert" onclick="closePopup()">
        <span aria-hidden="true"><svg role="presentation" width="15" height="15" viewBox="0 0 44 44" aria-hidden="true" focusable="false">
        <path d="M0.549989 4.44999L4.44999 0.549988L43.45 39.55L39.55 43.45L0.549989 4.44999Z" />
        <path d="M39.55 0.549988L43.45 4.44999L4.44999 43.45L0.549988 39.55L39.55 0.549988Z" />
        </svg></span>
    </button>
    <h3>Notice: {{title}}</h3>
    <p>{{content}}</p>
</div>

{% raw %}
<script>
    function closePopup() {{
        document.querySelector('.alert').style.display = 'none';
    }}
</script>
{% endraw %}
{%-endmacro-%}

browse/templates/audio_landing_page.html
{% extends "base.html" %}

{% block title %}Audio for {{abs_meta.arxiv_id_v}}{% endblock %}

{% block head %}
  {{ super() }}
  <link rel="stylesheet" media="screen" type="text/css" href="{{ url_for('static', filename='css/abs_audio.css') }}"/>
{% endblock head %}


{% block header_h1 %}
<h1>
<a href="{{ url_for('browse.home') }}">{{ config['BROWSE_SITE_LABEL'] }}</a> &gt
<a href="{{url_for('browse.abstract', arxiv_id=abs_meta.arxiv_id_v)}}">{{abs_meta.arxiv_id_v}}</a> &gt audio
</h1>
{% endblock %}

{% block content %}
<div>
    <div>
        <h1>Audio for {{abs_meta.arxiv_id}}: {{abs_meta.title}}</h1>
        <a href="{{url_for('browse.abstract', arxiv_id=abs_meta.arxiv_id_v)}}">< Return to abstract page</a>
        
        {% if 'alphaxiv' in audio_urls %}
            <div class="item-audio">
                <h2>alphaXiv Audio Lecture</h2>
                <p>AI-generated lecture on the paper designed to be concise, informative, and neutral. <a href="https://alphaxiv.org/abs/{{abs_meta.arxiv_id_v}}">Learn more about alphaXiv.</a></p>
                <p>
                    {% if audio_urls['alphaxiv'].url %}
                        <a class="button-audio" href="{{audio_urls['alphaxiv'].url}}">Visit alphaXiv to listen</a>
                    {% elif audio_urls['alphaxiv'].not_available_reason %}
                        {{audio_urls['alphaxiv'].not_available_reason}}
                    {% else %}
                        Paper not yet available from alphaXiv.
                    {% endif %}
                </p>
            </div>
        {% endif %}
        
        {% if 'sciencecast' in audio_urls %}
            <div class="item-audio">
                <h2>ScienceCast Audio Summary</h2>
                <p>60-second AI-generated audio summary created during paper submission process. <a href="https://sciencecast.org/">Learn more about ScienceCast.</a></p>
                <p>
                    {% if audio_urls['sciencecast'].url %}
                        <a class="button-audio" href="{{audio_urls['sciencecast'].url}}">Visit ScienceCast to listen</a>
                    {% elif audio_urls['sciencecast'].not_available_reason %}
                        {{audio_urls['sciencecast'].not_available_reason}}
                    {% else %}
                        Paper not yet available from Sciencecast.
                    {% endif %}
                </p>
            </div>
        {% endif %}

        {% if not audio_urls %}
            <div>No audio links for {{abs_meta.arxiv_id}}.</div>
        {% endif %}
    </div>

</div>

<script type="text/javascript" src="https://arxiv-org.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/xghl7j/b/0/c95134bc67d3a521bb3f4331beb9b804/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=3f0251b5"></script>
{% endblock %}

browse/templates/catchup.html
{%- extends "base.html" -%}
{% import "list/list_macros.html" as list_macros with context %}

{#Catchup is a varaiation of the new page, but for days in the past and has set pagination#}

{% block head %}
  {{super()-}}
  <script src="{{ url_for('static', filename='js/mathjaxToggle.min.js') }}" type="text/javascript"></script>
  <script type="text/javascript" language="javascript">mathjaxToggle();</script>
{% endblock head %}

{% block header_h1 %}
<div class="header-breadcrumbs">
  <a href="{{ url_for('.home') }}"><img src="{{ url_for('static', filename='images/arxiv-logo-one-color-white.svg') }}" alt="arxiv logo" style="height:40px;"/></a> <span>&gt;</span>
  <a href="{{url_for('.catchup_form',)}}">catchup</a>
  </div>
{% endblock %}

{%- block content %}
<div id='content-inner'>
<div id='dlpage'>
  <h1>Catchup results for {{subject.full_name}} on {{date.strftime("%a, %d %b %Y")}}</h1>

  {% block list_index %}
    <ul>
      {% for ityp in index_for_types %}
      <li><a href="{{ityp[1]}}#item{{ityp[2]}}">{{ityp[0]}}</a></li>
      {% endfor %}
    </ul>
    
  {% endblock %}

  {% block pre_items %}
    <div>
      {% if next_day is not none %}
        <a href="{{url_for('.catchup', subject=subject.id, date=next_day.strftime('%Y-%m-%d'), abs=include_abs, page=1 )}}">Continue to the next day</a>
        <br><br>
      {% endif %}
      
      Total of {{count}} entries for {{date.strftime("%a, %d %b %Y")}}
      {{catchup_pages()}}

    </div>
  {% endblock %}

  {% block items %}

    {% for sec in sub_sections_for_types %}
      {%if sec.visible%}
        {{ list_macros.item_list(sec.items, sec.heading) }}
      {% endif %}
    {% endfor %}

    {% if not (sub_sections_for_types[0].visible or sub_sections_for_types[1].visible or sub_sections_for_types[2].visible) %}
      <br>
      {% if page > 1 %}
        <div>
          No further updates for {{date.strftime("%a, %d %b %Y")}}
          <br>
          <a href="{{url_for('.catchup', subject=subject.id, date=date.strftime('%Y-%m-%d'), abs=include_abs, page=1 )}}">Go to page 1</a>
        </div>
      {% else %}
        <div>
          <p>No updates for {{date.strftime("%a, %d %b %Y")}}. There was either no announcement for this day, or no updates within the requested subject.</p>
        </div>
      {% endif %}
      <br>
    {% endif %}

  {% endblock %}

  {% block post_items %}
    <div></div>
    Total of {{count}} entries for {{date.strftime("%a, %d %b %Y")}}
      {{catchup_pages()}}
      
      {% if next_day is not none %}
        <br> <br>
        <a href="{{url_for('.catchup', subject=subject.id,  date=next_day.strftime('%Y-%m-%d'), abs=include_abs, page=1 )}}">Continue to the next day</a>
      {% endif %}
    </div>
  {% endblock %}

</div>
</div>
{%- endblock %}


{%- macro catchup_pages() -%}
  {% if paging | length > 0 %}
  View page:
    {%- for number, link in paging -%}

      {% if link == 'no-link' %}
        <span>{{number}}</span>
      {% else %}
        <a href={{link}}>{{number}}</a>
      {% endif %}

    {% endfor %}
  {% endif %}
{%- endmacro -%}

browse/templates/format.html
{% extends "base.html" %}
{% block title %}Format selector for {{arxiv_idv}}{% endblock %}
{% block header_h1 %}
<h1>
<a href="{{ url_for('browse.home') }}">{{ config['BROWSE_SITE_LABEL'] }}</a> &gt
<a href="{{url_for('browse.abstract', arxiv_id=arxiv_idv)}}">{{arxiv_idv}}</a> &gt format
</h1>
{% endblock %}

{% block content %}
<h1>Format selector for <a href="{{url_for('browse.abstract', arxiv_id=arxiv_idv)}}">{{arxiv_idv}}</a></h1>

<dl>

{% if pdf %}
<dt><b>PDF</b></dt>
<dd>
<form action="{{url_for('dissemination.pdf', arxiv_id=arxiv_idv)}}" method="get">
Now includes fonts, see our <a href="https://info.arxiv.org/help/pdf">PDF help</a>.
<input type="submit" value="Download PDF" />
</form>
<br />
</dd>
{% endif %}

{% if ps %}
<dt><b>Author supplied PostScript</b></dt>
<dd>
<form action="{{url_for('dissemination.ps', arxiv_id=arxiv_idv)}}" method="get">
Delivered via an additional HTML page if there are multiple files,
otherwise as a <b>PostScript</b> (.ps) file.
<input type="submit" value="Download PostScript" />
</form>
<br />
</dd>
{% endif %}

{% if dvi %}
<dt><b>DVI</b></dt>
<dd>
<form action="{{url_for('dissemination.dvi', arxiv_id=arxiv_idv)}}" method="get">
Delivered as a <b>gzipped DVI</b> (.dvi.gz) file or as a <b>gzipped tar</b>
(.tar.gz) file if there are figures to include.
<input type="submit" value="Download DVI" />
</form>
<br />
</dd>
{% endif %}

{% if html %}
<dt><b>HTML</b></dt>
<dd>
<form action="{{url_for('dissemination.html', arxiv_id=arxiv_idv)}}" method="get">
<input type="submit" value="Download HTML" />
</form>
<br />
</dd>
{% endif %}

{% if docx %}
<dt><b>DOCX</b></dt>
<dd>
<form action="{{url_for('src.src', arxiv_id_str=arxiv_idv)}}" method="get">
<input type="submit" value="Download DOCX" /><br />
Requires Word 2007 or earlier versions of Word with
<a href="http://www.microsoft.com/downloads/details.aspx?FamilyId=941B3470-3AE9-4AEE-8F43-C6BB74CD1466&displaylang=en">Microsoft
Office Compatibility Pack for Word, Excel, and PowerPoint 2007 File Formats</a>
to view/edit.
</form>
<br />
</dd>
{% endif %}

{% if src and not encrypted %}
<dt><b>Source</b></dt>
<dd>
Delivered as a <b>gzipped tar</b> (.tar.gz) file if there are multiple files,
otherwise as a <b>PDF</b> file, or a <b>gzipped TeX, DVI, PostScript or HTML</b>
(.gz, .dvi.gz, .ps.gz or .html.gz) file depending on submission format.
[ <a href="{{url_for('src.src', arxiv_id_str=arxiv_idv)}}">Download source</a> ]
<br />
</dd>
{% endif %}

</dl>

<p><b>Note:</b> Many of the formats above are served gzipped
(<code>Content-Encoding: x-gzip</code>). Your browser may silently uncompress
after downloading so the files you see saved may appear uncompressed.</p>

<p>Please report any problems to <a href="https://arxiv-org.atlassian.net/servicedesk/customer/portal/1">arXiv technical support</a> and include the paper identifier.</p>

{% endblock %}